create table if not exists public.fish (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  species text not null,
  color text
);

alter table public.fish enable row level security;

grant select, insert on table public.fish to anon;

drop policy if exists "Public can read fish" on public.fish;
drop policy if exists "Public can add fish" on public.fish;

create policy "Public can read fish"
  on public.fish
  for select
  to anon
  using (true);

create policy "Public can add fish"
  on public.fish
  for insert
  to anon
  with check (true);
